---
apiVersion: v1
kind: Secret
metadata:
  name: test-demo-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/openshift-tigerteam/test-demo-app-gitops